### ISSUE TITLE
Missing Image in Speakers

### ISSUE THREAD

**Issue by soumya-ch** [ICLR/iclr.github.io#10]
In speakers.html, the image of Profs. Yoshua Benjio and Yann LeCun is missing due to missing image source in speakers.yml. Also, their affiliations are interchanged.

https://github.com/ICLR/iclr.github.io/blob/3f3f482df2b5155bf352eee5d7bd22d7f6394bcf/static/speakers.yml#L26-L28

Possible fix:
```yaml
    - speaker: Profs. Yann LeCun and Yoshua Benjio
      image: static/lecun+bengio.png
      title: Reflections from the Turing Award Winners
      institution: Facebook AI + NYU / MILA
```
Rendered page:
The uniformity of the page is lost though.
![image](https://user-images.githubusercontent.com/33203398/78936600-86b2c000-7acc-11ea-97a8-5473e677d9df.png)

The image used (from Voices of ICLR2020: Announcing our Keynote Speakers Medium Blog) 
![lecun+bengio](https://user-images.githubusercontent.com/33203398/78936688-b06be700-7acc-11ea-865e-a0cad1881891.png)

If this is fine, I can submit a pr.
