### ISSUE TITLE
Document format of json and yaml files

### ISSUE THREAD

**Issue by srush** [ICLR/iclr.github.io#14]
We should have documentation for each of the files used for the data storage on the website.

**Comment by soumya-ch** [comment]
Can we also organise the static files into different folders like data, images, js, css, etc? The static folder looks too cluttered presently.

**Comment by srush** [comment]
sure.

**Comment by srush** [comment]
actually let's make this two separate things. This one is about the backend. You can organize the frontend files in `static/`

**Comment by soumya-ch** [comment]
I think this issue got closed by mistake.

Is this format below fine for the documentation? 
@srush, can you help fill in the `???` and socials.yml section? 
For sponsors, which file should be documented - `sponsors.yml` or `sponsors.tsv`?
I couldn't understand quite a few fields in `site_data.json` which is not documented in the following.

### faq.yml

```yaml
FAQ:
    - Section: SECTION_NAME
      QA:
        - Question: "QUESTION"
          Answer: "ANSWER"
        - Question:
          Answer:
        ... 
    - Section:
      QA:
        ...
```

### schedule.yml

#### Time Slots:
```yaml
# ALL TIMES have to be in UTC
time_slots:
  5a: [5:00 AM,7:00 AM]
  8a: [8:00 AM,10:00 AM]
  11a: [11:00 AM, 11:30 AM]
  12p: [12:00 PM, 2:00 PM]
  2p: [2:00 PM, 2:30 PM]
  4p: [4:00 PM, 4:30 PM]
  5p: [5:00 PM, 7:00 PM]
  7p: [7:00 PM, 7:30 PM]
  8p: [8:00 PM, 10:00 PM]
```

#### Events:
```yaml
conference:
    - day: "yyyy-mm-dd"
      events:
        - slot: # Slot id from the above time slots (eg 5a)
          type: poster/qa
          short: ???
        - slot:
          type:
          short:
        ...
    - day: ...
```

### socials.yml

```yaml
socials:
    - name: 
      organizers: 
      website:
    - name:
      organizers:
      website:
    ...
```

### speakers.yml

```yaml
speakers:
    - speaker: NAME(S)
      title: "Title of talk"
      image: # Path to image of speaker(s) in static/images
      institution: # Of the speaker(s)
    - speaker:
      title:
      image:
      institution:
    ...
```

### workshops.yml

```yaml
workshops:
    - name: NAME
      organizers: "Name1 · Name2 · Name3" 
      website: Link to Workshop Website
      chat: ???
    - name:
      organizers:
      website:
      chat:
```
